[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["cd attendance && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd attendance && python manage.py collectstatic --noinput"]

[start]
cmd = "cd attendance && python manage.py migrate && gunicorn attendance.wsgi --bind 0.0.0.0:$PORT"
